import { chromium } from 'playwright-core';
const [S] = process.argv.slice(2);
const browser = await chromium.launch({ channel: 'chrome', headless: true, args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1400, height: 900 }, locale: 'pt-BR' });
page.on('pageerror', (e) => console.log('ERR', e.message));
await page.goto('http://localhost:4711/login');
await page.fill('#password', 'dev');
await page.click('#submit');
await page.waitForURL((u) => !u.pathname.startsWith('/login'));
await page.evaluate(() => { localStorage.setItem('agent-office.profile', JSON.stringify({ name: 'Teste', color: '#ef476f', look: {} })); localStorage.removeItem('agent-office.code'); });
await page.goto('http://localhost:4711/');
await page.waitForFunction(() => window.__office && window.__office.store.floor, null, { timeout: 60000 });
await page.waitForTimeout(1500);
await page.locator('text=Ficar no 3D').click().catch(() => {});
await page.locator('.dock button', { hasText: 'Workers' }).first().click().catch(() => {});
await page.waitForTimeout(800);
await page.locator('#workers li').first().click();
await page.waitForTimeout(2000);
await page.locator('.term-tab-label', { hasText: 'Código' }).click();
await page.waitForSelector('.code-row', { timeout: 30000 });
const box = (sel) => page.evaluate((sel) => { const b = document.querySelector(sel).getBoundingClientRect(); return [Math.round(b.left), Math.round(b.right), Math.round(b.width), Math.round(b.height)]; }, sel);
console.log('side', await box('.code-side'), 'filter', await box('.code-filter'));
await page.fill('.code-filter', 'notes'); await page.keyboard.press('Enter'); await page.waitForTimeout(1200);
console.log('modal before', await box('.modal.term'));
await page.locator('.code-tool', { hasText: '⛶' }).click(); await page.waitForTimeout(800);
console.log('modal full', await box('.modal.term'));
await page.locator('.code-tool', { hasText: '↵' }).click();
await page.locator('.code-tool', { hasText: 'A+' }).click(); await page.locator('.code-tool', { hasText: 'A+' }).click();
const s = await box('.code-split');
await page.mouse.move(s[0] + 3, 400); await page.mouse.down(); await page.mouse.move(s[0] + 120, 400, { steps: 5 }); await page.mouse.up();
await page.waitForTimeout(800);
console.log('side after drag', await box('.code-side'), 'prefs', await page.evaluate(() => localStorage.getItem('agent-office.code')));
await page.screenshot({ path: `${S}/code-full.png` });
await browser.close();
